# jar cf jar-file input-file(s)
# jar tf *.jar  < lsits the files in the archive. >
# http://docs.oracle.com/javase/tutorial/deployment/jar/build.html


all:
	javac AddressBook.java

.PHONY: clean

clean:
	rm *.class